[platformio]
description = Zavepower spa WiFi module
default_envs = esp32s3
boards_dir = boards
data_dir = balboa-spa/dist

[libraries]
wifimanager32 = https://github.com/tzapu/WiFiManager.git#9f5981e
circularbuffer = rlogiacco/CircularBuffer @ ^1.3.3
pubsubclient = PubSubClient@2.8
arduinojson = ArduinoJson@6.18.3
ticker = sstaub/TickTwo@^4.4.0
arduinolog = thijse/ArduinoLog@1.1.1
crc8 = RobTillaart/CRC
base64 = https://github.com/Densaugeo/base64_arduino.git
espasyncwebserver = https://github.com/me-no-dev/ESPAsyncWebServer.git

[com-esp32-dev]
platform = espressif32@6.8.1
board = esp32dev
monitor_filters = esp32_exception_decoder
framework = arduino
build_type = debug
board_build.filesystem = littlefs
board_build.partitions = spa_module.csv
extra_scripts = pre:scripts/generate_flash_args.py, post:scripts/extra_script.py

build_flags =
  '-DLOG_LEVEL=LOG_LEVEL_VERBOSE'
  '-DCORE_DEBUG_LEVEL=3'
  '-DCONFIG_ESP_TASK_WDT=n'
  '-DCONFIG_ESP_INT_WDT=n'
  '-DCONFIG_ASYNC_TCP_USE_WDT=n'

lib_deps = 
	${libraries.wifimanager32}
	${libraries.circularbuffer}
	${libraries.pubsubclient}
	${libraries.arduinojson}
	${libraries.ticker}
	${libraries.arduinolog}
	${libraries.crc8}
	${libraries.base64}
	${libraries.espasyncwebserver}

[com-esp32s3]
platform = espressif32@6.8.1
board = esp32-s3-devkitc-1
monitor_filters = esp32_exception_decoder
framework = arduino
build_type = debug
board_build.filesystem = littlefs
board_build.partitions = spa_module.csv
extra_scripts = pre:scripts/generate_flash_args.py, post:scripts/extra_script.py

build_flags =
	'-DLOG_LEVEL=LOG_LEVEL_VERBOSE'
	'-DCORE_DEBUG_LEVEL=3'
    '-DARDUINO_USB_CDC_ON_BOOT=1'
	'-DCONFIG_ESP_TASK_WDT=n'
  	'-DCONFIG_ESP_INT_WDT=n'
	'-DCONFIG_ASYNC_TCP_USE_WDT=n'

lib_deps = 
	${libraries.wifimanager32}
	${libraries.circularbuffer}
	${libraries.pubsubclient}
	${libraries.arduinojson}
	${libraries.ticker}
	${libraries.arduinolog}
	${libraries.crc8}
	${libraries.base64}
	${libraries.espasyncwebserver}

[env:esp32-wroom-dev]
platform = ${com-esp32-dev.platform}
board =  ${com-esp32-dev.board}
monitor_filters = ${com-esp32-dev.monitor_filters}
framework = ${com-esp32-dev.framework}
build_type = ${com-esp32-dev.build_type}
board_build.filesystem = ${com-esp32-dev.board_build.filesystem}
board_build.partitions = ${com-esp32-dev.board_build.partitions}
extra_scripts = ${com-esp32-dev.extra_scripts}

lib_deps = ${com-esp32-dev.lib_deps}

build_flags =
  ${com-esp32-dev.build_flags}

monitor_port = COM9
monitor_speed = 115200
upload_port = COM9
upload_speed = 921600

[env:esp32s3]
platform = ${com-esp32s3.platform}
board =  ${com-esp32s3.board}
monitor_filters = ${com-esp32s3.monitor_filters}
framework = ${com-esp32s3.framework}
build_type = ${com-esp32s3.build_type}
board_build.filesystem = ${com-esp32s3.board_build.filesystem}
board_build.partitions = ${com-esp32s3.board_build.partitions}
extra_scripts = ${com-esp32s3.extra_scripts}

lib_deps = ${com-esp32s3.lib_deps}

build_flags =
  ${com-esp32s3.build_flags}
  
debug_tool = esp-prog
monitor_port = COM37
monitor_speed = 115200
upload_port = COM37
upload_speed = 921600